blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/ABladeLabs/mss-industries-product-configurator/discussions
    about: For questions and general discussions, please use GitHub Discussions
